# Generated by Django 4.2.2 on 2023-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удален'),
        ),
    ]
